/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package geometryoop.view.panels;

import geometryoop.model.ShapeType;
import java.util.HashMap;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author kaushik
 */
public class ButtonPanel extends javax.swing.JPanel {

    private HashMap<JRadioButton, ShapeType> hashMap;

    /**
     * Creates new form ButtonPanel
     */
    public ButtonPanel() {
        hashMap = new HashMap<>();
        initComponents();
        for (ShapeType shapeType : ShapeType.values()) {
            JRadioButton button = new JRadioButton(shapeType.toString());
            hashMap.put(button, shapeType);
            add(button);
            buttonGroup1.add(button);
        }
    }

    public ShapeType getSelectedShapeType() throws NoButtonSelectedException {
        for (JRadioButton button : hashMap.keySet()) {
            if (button.isSelected()) {
                return hashMap.get(button);
            }
        }
        throw new NoButtonSelectedException();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables

    public static class NoButtonSelectedException extends Exception {

        public NoButtonSelectedException() {
        }
    }
}
